services:

    _defaults:
        autowire: true
        public: false
        autoconfigure: true

    _instanceof:
        SolidWorx\SimpleResponseBundle\ResponseHandlerInterface:
            tags: ['solidworx.response_handler']

    SolidWorx\SimpleResponseBundle\ResponseHandler:
        arguments: [!tagged_iterator 'solidworx.response_handler']

    SolidWorx\SimpleResponseBundle\ResponseHandlerListener:
        tags: ['kernel.event_subscriber']

    # Core handlers
    SolidWorx\SimpleResponseBundle\Handler\TemplateResponseHandler: ~
    SolidWorx\SimpleResponseBundle\Handler\RouteRedirectHandler: ~
