services:

    _defaults:
        autowire: true
        public: false
        autoconfigure: true

    SolidWorx\SimpleResponseBundle\ResponseHandler: ~

    SolidWorx\SimpleResponseBundle\ResponseHandlerListener:
        tags: ['kernel.event_subscriber']

    # Core handlers
    SolidWorx\SimpleResponseBundle\Handler\TemplateResponseHandler:
        tags: ['response_handler.handler']

    SolidWorx\SimpleResponseBundle\Handler\RouteRedirectHandler:
        tags: ['response_handler.handler']
