services:

    simple_response_handler.handler:
        class: SolidWorx\SimpleResponseBundle\ResponseHandler

    simple_response_handler.event.listener:
        class: SolidWorx\SimpleResponseBundle\ResponseHandlerListener
        arguments: ['@simple_response_handler.handler']
        tags:
            - { name: kernel.event_subscriber }

    simple_response.handler.template_response:
        class: SolidWorx\SimpleResponseBundle\Handler\TemplateResponseHandler
        arguments: ['@templating']
        tags:
            - { name: 'response_handler.handler' }